### ISSUE TITLE
Compilation error when MICRORL_CFG_USE_ECHO_OFF=0

### ISSUE THREAD

**Issue by evgs** [dimmykar/microrl-remaster#6]
Some vars and definitions are still in use when option is set  MICRORL_CFG_USE_ECHO_OFF=0 (Release 2.4.0)

```
microrl.c:748:12: error: 'microrl_t' {aka 'struct microrl'} has no member named 'echo'
microrl.c:748:22: error: 'MICRORL_ECHO_ON' undeclared (first use in this function); did you mean 'MICRORL_ESC_END'?
```

btw, ECHO_OFF=0 is default fallback setting if not configured in user headers

**Comment by dimmykar** [comment]
Hello! I am very grateful to you that you reported the problem. Fixed a bug in patch v2.4.1
